### ISSUE TITLE
只清理特定后缀文件

### ISSUE THREAD

**Issue by rachpt** [tomorrow505/HUDBT_UPLOADER_V2.0#1]
https://github.com/tomorrow505/HUDBT_UPLOADER_V2.0/blob/9dddb450a02f7553c4769cec5893b9820e173251/main.py#L213

缓存文件夹里面的所有文件都会被删掉，而程序能产生的文件只有特定几种，建议只删特定后缀文件。

我把 缓存文件夹设成了 源 代码文件夹，代码被删了两次 :cry:

```python
                for file in filelist:
                    _, ext = os.path.splitext(file)
                    if ext in ['.torrent', '.jpg', '.log']:
                        os.remove(file)
```

**Comment by tomorrow505** [comment]
哈哈，好的，我以为都会新建一个文件夹呢。
